// THIS CODE WAS AUTO GENERATED. DO NOT CHANGE IT! 

using Lava.Raknet.Protocol;

namespace Lava.Raknet.Protocol.Types
{
	public sealed class ParticleIds
	{
		public const int BUBBLE = 1;
		public const int BUBBLE_MANUAL = 2;
		public const int CRITICAL = 3;
		public const int BLOCK_FORCE_FIELD = 4;
		public const int SMOKE = 5;
		public const int EXPLODE = 6;
		public const int EVAPORATION = 7;
		public const int FLAME = 8;
		public const int CANDLE_FLAME = 9;
		public const int LAVA = 10;
		public const int LARGE_SMOKE = 11;
		public const int REDSTONE = 12;
		public const int RISING_RED_DUST = 13;
		public const int ITEM_BREAK = 14;
		public const int SNOWBALL_POOF = 15;
		public const int HUGE_EXPLODE = 16;
		public const int HUGE_EXPLODE_SEED = 17;
		public const int BREEZE_WIND_EXPLOSION = 18;
		public const int MOB_FLAME = 19;
		public const int HEART = 20;
		public const int TERRAIN = 21;
		public const int SUSPENDED_TOWN = 22;
		public const int TOWN_AURA = 22;
		public const int PORTAL = 23;
		public const int SPLASH = 25;
		public const int WATER_SPLASH = 25;
		public const int WATER_SPLASH_MANUAL = 26;
		public const int WATER_WAKE = 27;
		public const int DRIP_WATER = 28;
		public const int DRIP_LAVA = 29;
		public const int DRIP_HONEY = 30;
		public const int STALACTITE_DRIP_WATER = 31;
		public const int STALACTITE_DRIP_LAVA = 32;
		public const int FALLING_DUST = 33;
		public const int DUST = 33;
		public const int MOB_SPELL = 34;
		public const int MOB_SPELL_AMBIENT = 35;
		public const int MOB_SPELL_INSTANTANEOUS = 36;
		public const int INK = 37;
		public const int SLIME = 38;
		public const int RAIN_SPLASH = 39;
		public const int VILLAGER_ANGRY = 40;
		public const int VILLAGER_HAPPY = 41;
		public const int ENCHANTMENT_TABLE = 42;
		public const int TRACKING_EMITTER = 43;
		public const int NOTE = 44;
		public const int WITCH_SPELL = 45;
		public const int CARROT = 46;
		public const int MOB_APPEARANCE = 47;
		public const int END_ROD = 48;
		public const int DRAGONS_BREATH = 49;
		public const int SPIT = 50;
		public const int TOTEM = 51;
		public const int FOOD = 52;
		public const int FIREWORKS_STARTER = 53;
		public const int FIREWORKS_SPARK = 54;
		public const int FIREWORKS_OVERLAY = 55;
		public const int BALLOON_GAS = 56;
		public const int COLORED_FLAME = 57;
		public const int SPARKLER = 58;
		public const int CONDUIT = 59;
		public const int BUBBLE_COLUMN_UP = 60;
		public const int BUBBLE_COLUMN_DOWN = 61;
		public const int SNEEZE = 62;
		public const int SHULKER_BULLET = 63;
		public const int BLEACH = 64;
		public const int DRAGON_DESTROY_BLOCK = 65;
		public const int MYCELIUM_DUST = 66;
		public const int FALLING_RED_DUST = 67;
		public const int CAMPFIRE_SMOKE = 68;
		public const int TALL_CAMPFIRE_SMOKE = 69;
		public const int DRAGON_BREATH_FIRE = 70;
		public const int DRAGON_BREATH_TRAIL = 71;
		public const int BLUE_FLAME = 72;
		public const int SOUL = 73;
		public const int OBSIDIAN_TEAR = 74;
		public const int PORTAL_REVERSE = 75;
		public const int SNOWFLAKE = 76;
		public const int VIBRATION_SIGNAL = 77;
		public const int SCULK_SENSOR_REDSTONE = 78;
		public const int SPORE_BLOSSOM_SHOWER = 79;
		public const int SPORE_BLOSSOM_AMBIENT = 80;
		public const int WAX = 81;
		public const int ELECTRIC_SPARK = 82;
		public const int SHRIEK = 83;
		public const int SCULK_SOUL = 84;
		public const int SONIC_EXPLOSION = 85;
		public const int BRUSH_DUST = 86;
		public const int CHERRY_LEAVES = 87;
		public const int DUST_PLUME = 88;
		public const int WHITE_SMOKE = 89;
		public const int VAULT_CONNECTION = 90;
		public const int WIND_EXPLOSION = 91;
		public const int WOLF_ARMOR_CRACK = 92;
	}
}
